# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-14 16:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.fields
import django_enumfield.item
import loyalty.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySchemeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', django_enumfield.fields.EnumField([django_enumfield.item.Item(10, 'Nectar')], choices=[(django_enumfield.item.Item(10, 'Nectar'), 'Nectar')])),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MondoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mondo_user_id', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=512)),
                ('access_expires', models.DateTimeField()),
                ('refresh_token', models.CharField(max_length=512)),
                ('user', loyalty.core.fields.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mondo_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loyaltyschemelink',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='accounts.MondoUser'),
        ),
    ]
