# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-14 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20151114_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mondo_account_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
