# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-15 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django_enumfield.fields
import django_enumfield.item


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notifiedtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyschemelink',
            name='erroring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loyaltyschemelink',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loyaltyschemelink',
            name='scheme',
            field=django_enumfield.fields.EnumField([django_enumfield.item.Item(10, 'Nectar'), django_enumfield.item.Item(20, 'Sparks')], choices=[(django_enumfield.item.Item(10, 'Nectar'), 'Nectar'), (django_enumfield.item.Item(20, 'Sparks'), 'Sparks')]),
        ),
    ]
